version: '1.0'
services:
  backend:
    container_name: go-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
       condition: service_healthy
    environment:
      MYSQL_DATABASE: go_app_dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ADDRESS: dockerMysql:3307

  db:
    image: mysql
    restart: always
    container_name: dockerMysql
    ports:
      - '3307:3307'
    expose:
      - '3307'
    environment:
      MYSQL_DATABASE: go_app_dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 10s
      retries: 10